Noun = 'Noun'
Pronoun = 'Pronoun'
Number = 'Number'
Josa = 'Josa'
Adjective = 'Adjective'
Verb = 'Verb'
Eomi = 'Eomi'
Adverb = 'Adverb'
Determiner = 'Determiner'
Exclamation = 'Exclamation'

BOS = 'BOS'
EOS = 'EOS'

Unk = 'Unknown'
